# Generated by Django 4.2.2 on 2023-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(max_length=5000),
        ),
    ]
