# Generated by Django 4.2.2 on 2023-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deslike',
            field=models.IntegerField(default=0),
        ),
    ]
