# Generated by Django 4.2.2 on 2023-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_post_deslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typeOfChoice',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Music'), (3, 'Series/Movies'), (4, 'Sports')], default=1),
        ),
    ]
